name: Node CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Ensure react-scripts@5.0.1 is installed
        run: npm install react-scripts@5.0.1

      - name: Audit and fix non-breaking vulnerabilities
        run: npm audit fix

      - name: Print audit report (for visibility)
        run: npm audit || true

      - name: Run npm build
        run: npm run build
